# For the field url, replace the string "jdbc:sqlite::memory:" with a reference to your local database file "jdbc:sqlite:/home/user/projects/products-service/sqlite.db"
# Set the value of initialization-mode from always to never, because you’ve already initialized the database when running cds deploy --to sqlite.
---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:/home/user/projects/products-service/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
